name: 'Get tag name'
description: 'Gets current tag name and puts it into an environment variable GITHUB_TAG_NAME.'
author: 'Oleg Tarasov'
runs:
  using: 'node12'
  main: 'lib/main.js'
outputs:
  tag:
    description: The tag name.
branding:
  icon: 'tag'
  color: 'orange'